{
  "openapi": "3.0.0",
  "info": {
    "title": "API Times da Serie A de 2022",
    "description": "API para CRUD de Times da Serie A de 2022",
    "termsOfService": "",
    "contact": {
      "email": "uri.dantas@hotmail.com"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:3001",
      "description": "API de teste"
    },
    {
      "url": "https://api-teamsbrazilian2022.herokuapp.com",
      "description": "API de produção"
    }
  ],
  "paths": {
    "/users/create": {
      "post": {
        "summary": "Criar novo usuário",
        "description": "Rota responsável por criar novo usuário",
        "tags": ["User"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Users"
              },
              "examples": {
                "Users": {
                  "value": {
                    "name": "Iuri Dantas",
                    "username": "IuriDantas",
                    "email": "uri.dantas@hotmail.com",
                    "password": "blueed",
                    "photo": "https://avatars.githubusercontent.com/u/88010013?v=4"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Users"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },
    "/users": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "summary": "Lista de todos os usuários",
        "description": "Rota responsável por listar todos os usuários",
        "tags": ["User"],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Users"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "summary": "Login na API",
        "description": " Rota responsável pelo login",
        "tags": ["Auth"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Users"
              },
              "examples": {
                "User": {
                  "value": {
                    "email": "uri.dantas@hotmail.com",
                    "password": "blueed"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },
    "/seriea": {
      "get": {
        "summary": "Lista de todos os times",
        "description": "Rota responsável por listar todos os times",
        "tags": ["Serie A"],
        "responses": {
          "404": {
            "description": "Not Found"
          },
          "200": {
            "description": "ok",
            "content": {
              "appliation/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/teamsbrazilian2022"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/seriea/find/{id}": {
      "get": {
        "summary": "Busca um time pelo ID",
        "description": "Rota responsável por buscar um time pelo ID",
        "tags": ["Serie A"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id do time para a busca",
            "required": true
          }
        ],
        "responses": {
          "400": {
            "description": "Bad Request"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/teamsbrazilian2022"
                }
              }
            }
          }
        }
      }
    },
    "/seriea/create": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "summary": "Cadastrar um time",
        "description": "Rota responsável por cadastrar um time",
        "tags": ["Serie A"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/teamsbrazilian2022"
              },
              "examples": {
                "Rickandmortys": {
                  "value": {
                    "name": "América Futebol Clube",
                    "foundation": 1912,
                    "shield": "https://s.sde.globo.com/media/organizations/2019/02/28/America-MG-VERDE-fev2019-01.svg",
                    "mascot": "Coelho",
                    "localization": "Belo Horizonte"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Bad Request"
          },
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/teamsbrazilian2022"
                }
              }
            }
          }
        }
      }
    },
    "/seriea/update/{id}": {
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "summary": "Editar um time pelo ID",
        "description": "Rota responsável por editar um time pelo ID",
        "tags": ["Serie A"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id do time para a busca",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/teamsbrazilian2022"
              },
              "examples": {
                "Paletas": {
                  "value": {
                    "name": "América Futebol Clube editado",
                    "foundation": 1912,
                    "shield": "https://s.sde.globo.com/media/organizations/2019/02/28/America-MG-VERDE-fev2019-01.svg",
                    "mascot": "Coelho",
                    "localization": "Belo Horizonte"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Bad Request"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/teamsbrazilian2022"
                }
              }
            }
          }
        }
      }
    },
    "/seriea/delete/{id}": {
      "delete": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "summary": "Apagar um time pelo ID",
        "description": "Rota responsável por apagar um time pelo ID",
        "tags": ["Serie A"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id do time para deleção",
            "required": true
          }
        ],
        "responses": {
          "400": {
            "description": "Bad Request"
          },
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/seriea/search": {
      "get": {
        "summary": "Busca um time pelo nome",
        "description": "Rota responsável por buscar um time pelo nome",
        "tags": ["Serie A"],
        "parameters": [
          {
            "in": "query",
            "name": "name",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/teamsbrazilian2022"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/serieb": {
      "get": {
        "summary": "Lista de todos os times",
        "description": "Rota responsável por listar todos os times",
        "tags": ["Serie B"],
        "responses": {
          "404": {
            "description": "Not Found"
          },
          "200": {
            "description": "ok",
            "content": {
              "appliation/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/teamsbrazilian2022"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/serieb/find/{id}": {
      "get": {
        "summary": "Busca um time pelo ID",
        "description": "Rota responsável por buscar um time pelo ID",
        "tags": ["Serie B"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id do time para a busca",
            "required": true
          }
        ],
        "responses": {
          "400": {
            "description": "Bad Request"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/teamsbrazilian2022"
                }
              }
            }
          }
        }
      }
    },
    "/serieb/create": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "summary": "Cadastrar um time",
        "description": "Rota responsável por cadastrar um time",
        "tags": ["Serie B"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/teamsbrazilian2022"
              },
              "examples": {
                "Rickandmortys": {
                  "value": {
                    "name": "Cruzeiro Esporte Clube",
                    "foundation": 1921,
                    "shield": "https://s.sde.globo.com/media/organizations/2021/02/13/cruzeiro_2021.svg",
                    "mascot": "Raposa",
                    "localization": "Belo Horizonte"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Bad Request"
          },
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/teamsbrazilian2022"
                }
              }
            }
          }
        }
      }
    },
    "/serieb/update/{id}": {
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "summary": "Editar um time pelo ID",
        "description": "Rota responsável por editar um time pelo ID",
        "tags": ["Serie B"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id do time para a busca",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/teamsbrazilian2022"
              },
              "examples": {
                "Paletas": {
                  "value": {
                    "name": "Cruzeiro Esporte Clube editado",
                    "foundation": 1921,
                    "shield": "https://s.sde.globo.com/media/organizations/2021/02/13/cruzeiro_2021.svg",
                    "mascot": "Raposa",
                    "localization": "Belo Horizonte"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Bad Request"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/teamsbrazilian2022"
                }
              }
            }
          }
        }
      }
    },
    "/serieb/delete/{id}": {
      "delete": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "summary": "Apagar um time pelo ID",
        "description": "Rota responsável por apagar um time pelo ID",
        "tags": ["Serie B"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id do time para deleção",
            "required": true
          }
        ],
        "responses": {
          "400": {
            "description": "Bad Request"
          },
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/serieb/search": {
      "get": {
        "summary": "Busca um time pelo nome",
        "description": "Rota responsável por buscar um time pelo nome",
        "tags": ["Serie B"],
        "parameters": [
          {
            "in": "query",
            "name": "name",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/teamsbrazilian2022"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "schemas": {
      "teamsbrazilian2022": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "foundation": {
            "type": "number"
          },
          "shield": {
            "type": "string"
          },
          "mascot": {
            "type": "string"
          },
          "localization": {
            "type": "string"
          }
        }
      },
      "Users": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "username": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "photo": {
            "type": "string"
          }
        }
      }
    }
  }
}
